# Copyright (c) 2020-2021 NorthStart
#
# This file is part of NorthStarFleet2025-project.
#
# NorthStarFleet2025-project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# NorthStarFleet2025-project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NorthStarFleet2025-project.  If not, see <https://www.gnu.org/licenses/>.

from os.path import abspath

Import("env")
Import("args")
Import("sources")


if args["TARGET_ENV"] == "tests":
    print("etss")
    env_cpy = env.Clone()

    # Append on the global robot target build flag
    env_cpy.AppendUnique(CCFLAGS=["-D " + args["ROBOT_TYPE"]])

    # add on the macro for the remote type
    env_cpy.AppendUnique(CCFLAGS=["-D " + args["REMOTE_TYPE"]])
    
    rawSrcs = env_cpy.FindSourceFiles(".")

    for source in rawSrcs:
        sources.append(env_cpy.Object(source))

Return('sources')
